Repository mattermost/mattermost-plugin-apps, pull requests merged in 2020-09, with the labels that each got.

#1 copied circleci.yml from demo
  .circleci/config.yml
Labels: 3: Reviews Complete

#2 Initial skeleton
  CODEOWNERS
  Makefile
  assets/profile.png
  go.mod
  go.sum
  plugin.json
  server/cloudapps/app.go
  server/cloudapps/app_get.go
  server/cloudapps/app_install.go
  server/cloudapps/app_list.go
  server/cloudapps/expand.go
  server/cloudapps/on_user_joined_channel.go
  server/cloudapps/placeholder_structs.go
  server/cloudapps/proxy.go
  server/cloudapps/registry.go
  server/cloudapps/subscription.go
  server/cloudapps/subscriptions.go
  server/command/command.go
  server/command/info.go
  server/command/main.go
  server/configuration.go
  server/configurator/config.go
  server/configurator/configurator.go
  server/configurator/test_service.go
  server/constants/constants.go
  server/main.go
  server/manifest.go
  server/plugin.go
  server/plugin/plugin.go
  server/plugin_test.go
  server/utils/byte_size.go
  server/utils/errors.go
  server/utils/md/markdown.go
Labels: 3: Reviews Complete

#6 Prep for renaming the repo
  go.mod
  plugin.json
  server/apps/app.go
  server/apps/app_get.go
  server/apps/app_install.go
  server/apps/app_list.go
  server/apps/expand.go
  server/apps/on_user_joined_channel.go
  server/apps/placeholder_structs.go
  server/apps/proxy.go
  server/apps/registry.go
  server/apps/subscription.go
  server/apps/subscriptions.go
  server/command/command.go
  server/command/info.go
  server/command/main.go
  server/constants/constants.go
  server/main.go
  server/manifest.go
  server/plugin/plugin.go
Labels: 3: Reviews Complete

#5 MM-28442: JWT, Incorporated much of Install/Authorize POC, cleanup
  go.mod
  go.sum
  server/apps/app.go
  server/apps/app_install.go
  server/apps/expand.go
  server/apps/get_app.go
  server/apps/install_app.go
  server/apps/list_apps.go
  server/apps/on_user_joined_channel.go
  server/apps/proxy.go
  server/apps/registry.go
  server/apps/service.go
  server/apps/subscriptions.go
  server/command/command.go
  server/command/info.go
  server/command/install.go
  server/command/main.go
  server/command/service.go
  server/configurator/configurator.go
  server/configurator/test_service.go
  server/constants/constants.go
  server/http/dialog/dialog.go
  server/http/dialog/install.go
  server/http/helloapp/helloapp.go
  server/http/service.go
  server/plugin/plugin.go
  server/utils/httputils/handler.go
  server/utils/httputils/limited_readcloser.go
  server/utils/httputils/limited_readcloser_test.go
  server/utils/httputils/utils.go
  server/utils/httputils/utils_test.go
  server/utils/md/markdown.go
  server/utils/utils.go
Labels: 2: Dev Review

#3 Initial data structs for forms, autocomplete, and modals
  server/apps/autocomplete.go
  server/apps/form.go
  server/apps/modal.go
Labels: 3: Reviews Complete

#7 Add OAuth App creation
  server/apps/app.go
  server/apps/install_app.go
  server/http/dialog/install.go
  server/http/helloapp/helloapp.go
  server/http/service.go
Labels: 2: Dev Review

#13 Hello App Install Wish with Bot token and OAuth
  go.mod
  go.sum
  server/apps/api.go
  server/apps/api_call.go
  server/apps/api_install_app.go
  server/apps/app.go
  server/apps/call.go
  server/apps/client.go
  server/apps/expand.go
  server/apps/form.go
  server/apps/get_app.go
  server/apps/hooks.go
  server/apps/location.go
  server/apps/modal.go
  server/apps/placeholder_structs.go
  server/apps/proxy.go
  server/apps/registry.go
  server/apps/service.go
  server/apps/wish.go
  server/command/info.go
  server/command/install.go
  server/command/main.go
  server/command/service.go
  server/configurator/configurator.go
  server/http/dialog/install.go
  server/http/helloapp/helloapp.go
  server/http/helloapp/install.go
  server/http/helloapp/manifest.go
  server/http/helloapp/oauth.go
  server/plugin/plugin.go
  server/utils/httputils/utils.go
Labels: 3: Reviews Complete

#14 Fixed go.mod to point at most current plugin-api
  go.mod
  go.sum
Labels: 4: Reviews Complete
