Repository mattermost/mattermost-plugin-apps, pull requests merged in 2021-07, with the labels that each got.

#210 Drop custom bash completion in favour of default one
  Makefile
  cmd/appsctl/completion.go
  cmd/appsctl/main.go
  go.mod
  go.sum
Labels: 4: Reviews Complete, Docs/Not Needed

#214 get the path value from the request, not the request values
  examples/go/hello-webhooks/hello.go
Labels: 4: Reviews Complete

#212 Add link in README to community server Apps channel
  README.md
Labels: 4: Reviews Complete

#195 Update AutocompletePosition documentation
  apps/field.go
Labels: Docs/Needed

#207 [MM-36240] Add commands to enable/disable apps
  apps/manifest.go
  apps/mmclient/mattermost_client.go
  apps/mmclient/mattermost_client_pp.go
  examples/go/hello-lambda/go.mod
  examples/go/hello-lambda/go.sum
  examples/go/hello-lifecycle/hello.go
  examples/go/hello-lifecycle/icon.png
  examples/go/hello-lifecycle/manifest.json
  examples/go/hello/builtin_hello/helloapp.go
  examples/go/hello/helloapp.go
  examples/go/hello/http_hello/helloapp.go
  go.mod
  go.sum
  server/command/debug.go
  server/command/enable.go
  server/command/list.go
  server/command/service.go
  server/command/uninstall.go
  server/httpin/dialog/install.go
  server/mocks/mock_proxy/mock_proxy.go
  server/mocks/mock_store/mock_appkv.go
  server/proxy/enable.go
  server/proxy/install.go
  server/proxy/list.go
  server/proxy/service.go
  server/proxy/uninstall.go
  server/store/appkv.go
  utils/utils.go
Labels: 4: Reviews Complete

#211 [MM-36659] Check for valid HomepageURL
  Makefile
  apps/app_test.go
  apps/manifest.go
  apps/manifest_test.go
  utils/url.go
  utils/url_test.go
Labels: 4: Reviews Complete, Docs/Not Needed

#221 Use Zap logger
  cmd/appsctl/aws.go
  cmd/appsctl/generate_terraform.go
  cmd/appsctl/log.go
  cmd/appsctl/main.go
  cmd/appsctl/provision.go
  examples/go/hello/http_hello/helloapp.go
  go.mod
  server/command/service.go
  server/config/service.go
  server/httpin/dialog/dialog.go
  server/httpin/dialog/install.go
  server/httpin/gateway/gateway.go
  server/httpin/gateway/oauth2.go
  server/httpin/gateway/static.go
  server/httpin/restapi/bindings_test.go
  server/httpin/restapi/call.go
  server/httpin/restapi/call_test.go
  server/httpin/restapi/kv_test.go
  server/httpin/restapi/restapi.go
  server/httpin/service.go
  server/logger/logger.go
  server/plugin.go
  server/proxy/bindings.go
  server/proxy/bindings_test.go
  server/proxy/enable.go
  server/proxy/install.go
  server/proxy/proxy.go
  server/proxy/proxy_test.go
  server/proxy/service.go
  server/proxy/synchronize.go
  server/proxy/uninstall.go
  server/store/apps.go
  server/store/manifest.go
  server/store/oauth2_test.go
  server/store/service.go
  server/store/service_test.go
  server/store/subscriptions_test.go
  upstream/upaws/clean.go
  upstream/upaws/client.go
  upstream/upaws/client_lambda.go
  upstream/upaws/initialize.go
  upstream/upaws/provision_app.go
  upstream/upaws/provision_data.go
  utils/zap_logger.go
Labels: 4: Reviews Complete
