Repository mattermost/mattermost-plugin-apps, pull requests merged in 2021-04, with the labels that each got.

#125 [MM-34234] Require user in http hello survey
  server/examples/go/hello/send_survey.go
Labels: 3: QA Review

#123 [MM-33020] Make app ID validation more strict
  apps/app.go
  apps/app_test.go
  apps/manifest.go
  server/command/debug.go
Labels: 3: QA Review, Docs/Done

#128 updated mocks
  server/mocks/mock_appservices/mock_appservices.go
  server/mocks/mock_proxy/mock_proxy.go
Labels: 4: Reviews Complete

#129 [MM-34522] Add autocomplete suggestions
  server/command/main.go
  server/command/service.go
Labels: 2: Dev Review

#114 [MM-32599] Implement webhook handler for App Framework
  apps/app.go
  apps/manifest.go
  apps/permissions.go
  server/config/config.go
  server/config/service.go
  server/examples/go/hello-webhooks/bindings.json
  server/examples/go/hello-webhooks/hello.go
  server/examples/go/hello-webhooks/icon.png
  server/examples/go/hello-webhooks/info_form.json
  server/examples/go/hello-webhooks/manifest.json
  server/examples/go/hello-webhooks/send_form.json
  server/http/dialog/install.go
  server/http/gateway/gateway.go
  server/http/gateway/oauth2.go
  server/http/gateway/static.go
  server/http/gateway/webhook.go
  server/proxy/expand.go
  server/proxy/install.go
  server/proxy/oauth2.go
  server/proxy/proxy.go
  server/proxy/service.go
Labels: 2: Dev Review, Docs/Needed

#130 [MM-34581] Add check that mocks are up to date to CI
  .circleci/config.yml
Labels: 4: Reviews Complete, Docs/Not Needed

#132 fixed mocks
  server/mocks/mock_proxy/mock_proxy.go
Labels: 4: Reviews Complete

#131 [MM-34491] Don't overwrite root command label
  docs/01-anatomy-hello.md
  docs/06-using-3rdparty-api.md
  server/examples/go/hello-oauth2/bindings.json
  server/examples/go/helloworld/bindings.json
  server/proxy/bindings.go
  server/proxy/bindings_test.go
Labels: 4: Reviews Complete, Docs/Done

#134 Minor fixes regarding OAuth
  apps/call.go
  server/proxy/oauth2.go
Labels: 4: Reviews Complete

#115 [MM-32330] E2E webapp tests
  .gitignore
  e2e/.eslintrc
  e2e/.gitignore
  e2e/cypress.json
  e2e/cypress/integration/bindings/channel_header_spec.ts
  e2e/cypress/plugins/index.ts
  e2e/cypress/support/index.d.ts
  e2e/cypress/support/index.ts
  e2e/cypress/tsconfig.json
  e2e/package-lock.json
  e2e/package.json
  server/examples/go/hello/install.go
  server/examples/go/hello/send_survey.go
  server/plugin.go
Labels: 4: Reviews Complete, Docs/Not Needed

#119 Apps metadata for client
  apps/app.go
  apps/call.go
  server/proxy/proxy.go
  server/proxy/proxy_test.go
  server/proxy/service.go
Labels: 4: Reviews Complete

#137 Generate mocks
  server/mocks/mock_proxy/mock_proxy.go
Labels: 2: Dev Review

#133 Webhook follow up
  server/http/gateway/oauth2.go
  server/http/gateway/static.go
  server/http/gateway/webhook.go
  server/proxy/install.go
  server/proxy/proxy.go
Labels: 4: Reviews Complete

#118 [MM-34237] Fix appsctl asset bug
  aws/provision_app.go
  aws/provision_data.go
Labels: 2: Dev Review, Docs/Not Needed

#135 Fix get bindings when expanding the user
  server/http/gateway/static.go
  server/http/restapi/bindings.go
  server/http/restapi/marketplace.go
Labels: 4: Reviews Complete, Awaiting Submitter Action, Docs/Not Needed

#50 MM-29584: Make apps plugin hook invocation/registration conditional
  .circleci/config.yml
  go.mod
  go.sum
  server/http/restapi/main_test.go
  server/http/restapi/restapitestlib.go
  server/plugin.go
Labels: 4: Reviews Complete, Docs/Not Needed

#104 Provision documentation
  docs/07-lifecycle.md
  docs/imgs/install-mm-aws-app.png
  docs/imgs/provisioning-in-3rd-party-aws.png
  docs/imgs/provisioning-in-mm-aws.png
Labels: 4: Reviews Complete

#140 Fix double marshalling
  aws/client.go
  aws/lambda.go
Labels: 4: Reviews Complete, Docs/Not Needed

#124 [MM-34457] Add E2E webapp tests to CI
  .circleci/config.yml
  apps/manifest.go
  e2e/package.json
  server/examples/go/hello/http_hello/helloapp.go
Labels: 2: Dev Review, Docs/Not Needed

#141 Drop term "Cloud Apps"
  plugin.json
  server/command/info.go
  server/command/service.go
  server/manifest.go
Labels: 4: Reviews Complete, Docs/Not Needed

#136 Add headers for static assets
  server/http/gateway/static.go
Labels: 4: Reviews Complete, Docs/Not Needed

#144 [MM-34661 Move examples into own directory
  assets/example-aws-hello.json
  docs/00-toc.md
  docs/01-anatomy-hello.md
  docs/06-using-3rdparty-api.md
  examples/go/hello-oauth2/bindings.json
  examples/go/hello-oauth2/configure_form.json
  examples/go/hello-oauth2/connect_form.json
  examples/go/hello-oauth2/hello.go
  examples/go/hello-oauth2/icon.png
  examples/go/hello-oauth2/manifest.json
  examples/go/hello-oauth2/send_form.json
  examples/go/hello-webhooks/bindings.json
  examples/go/hello-webhooks/hello.go
  examples/go/hello-webhooks/icon.png
  examples/go/hello-webhooks/info_form.json
  examples/go/hello-webhooks/manifest.json
  examples/go/hello-webhooks/send_form.json
  examples/go/hello/bindings.go
  examples/go/hello/builtin_hello/helloapp.go
  examples/go/hello/helloapp.go
  examples/go/hello/http_hello/functions.go
  examples/go/hello/http_hello/helloapp.go
  examples/go/hello/install.go
  examples/go/hello/send_survey.go
  examples/go/hello/submit_survey.go
  examples/go/hello/survey.go
  examples/go/hello/user_joined_channel.go
  examples/go/helloworld/bindings.json
  examples/go/helloworld/hello.go
  examples/go/helloworld/icon.png
  examples/go/helloworld/manifest.json
  examples/go/helloworld/send_form.json
  examples/js/aws_hello/hello_app/manifest.json
  examples/js/aws_hello/hello_app/on_activate/index.js
  examples/js/aws_hello/helloapp.go
  server/plugin.go
Labels: 4: Reviews Complete, Docs/Not Needed

#142 Manage permissions on bot creation
  apps/context.go
  server/proxy/install.go
Labels: 4: Reviews Complete

#149 Version bump 0.3.0
  plugin.json
  server/manifest.go
Labels: 2: Dev Review, QA Review Done

#145 Added Developer Docs link to README
  README.md
  apps/package.go
  assets/app-test-zendesk.json
  assets/example-aws-hello.json
  assets/manifests.json
  assets/profile.png
  docs/index.md
Labels: 4: Reviews Complete, Docs/Done

#156 Add profile picture back
  assets/profile.png
Labels: 2: Dev Review, Docs/Not Needed

#138 Add API for clients to check the bots and oauth apps ids
  apps/mmclient/mattermost_client_pp.go
  server/http/restapi/get_ids.go
  server/http/restapi/restapi.go
  server/utils/utils.go
Labels: 4: Reviews Complete, Docs/Not Needed

#150 MM_34997: disabled user consent option in app install dialog
  server/http/dialog/install.go
Labels: 4: Reviews Complete, AutoMerge, QA Review Done

#147 Store refreshed token
  examples/go/hello-oauth2/hello.go
Labels: 4: Reviews Complete, Docs/Not Needed

#155 [MM-35034] Clear ExpandedContext before passing it to the App
  server/proxy/proxy.go
Labels: 4: Reviews Complete

#154 [MM-34876] Change profile image
  assets/profile.png
Labels: 4: Reviews Complete, Docs/Not Needed

#151 Drop zendesk and awsHello from manifests file
  assets/.gitkeep
  assets/manifests.json
Labels: 4: Reviews Complete

#152 [MM-34993] Add Experimental label to all apps
  server/proxy/list.go
Labels: 4: Reviews Complete

#161 replaced hello icon
  examples/go/hello/bindings.go
Labels: 4: Reviews Complete, Docs/Not Needed

#160 properly de/re-activate app bot accounts
  apps/app.go
  server/proxy/auth.gogo
  server/proxy/expand.go
  server/proxy/install.go
  server/proxy/uninstall.go
Labels: 4: Reviews Complete, Docs/Not Needed

#159 Enable OAuth and Bot accounts for E2E tests
  e2e/cypress/integration/bindings/channel_header_spec.ts
  server/command/service.go
  server/config/service.go
Labels: 4: Reviews Complete, Docs/Not Needed

#157 [MM-34928] When Enable Bot Accounts setting is disabled, show message to admin when they run an /apps slash command
  server/command/service.go
Labels: 4: Reviews Complete, Docs/Not Needed

#162 Release v0.4.0
  plugin.json
  server/manifest.go
Labels: 4: Reviews Complete, Docs/Not Needed

#165 Introduce ReadOnly property for form fields
  apps/field.go
Labels: 4: Reviews Complete, Docs/Needed

#158 Refresh bindings when OAuth2 process is complete
  docs/06-using-3rdparty-api.md
  server/proxy/bindings.go
  server/proxy/enable.go
  server/proxy/install.go
  server/proxy/oauth2.go
  server/proxy/uninstall.go
Labels: Docs/Needed, QA Review Done

#55 add multiselect field option
  apps/field.go
Labels: 4: Reviews Complete, Docs/Not Needed

#169 [MM-35089] Improve error and call logging
  server/http/dialog/install.go
  server/http/gateway/oauth2.go
  server/http/gateway/static.go
  server/http/restapi/call.go
  server/logger/logger.go
  server/proxy/bindings.go
Labels: 4: Reviews Complete, Docs/Not Needed

#164 [MM-35102] Move docs to https://developers.mattermost.com
  README.md
  apps/package.go
  docs/01-anatomy-hello.md
  docs/02-example-post-menu.md
  docs/03-example-interactivity.md
  docs/05-using-mattermost-api.md
  docs/06-using-3rdparty-api.md
  docs/07-lifecycle.md
  docs/imgs/install-mm-aws-app.png
  docs/imgs/provisioning-in-3rd-party-aws.png
  docs/imgs/provisioning-in-mm-aws.png
  docs/index.md
Labels: 4: Reviews Complete

#167 [MM-34982] Add Zendesk 0.2.0 to manifest list
  assets/manifests.json
Labels: 4: Reviews Complete

#170 Make getOAuth2User use interface{} and not map[string]interface{} to unmarshal the value
  server/http/restapi/oauth2.go
Labels: 4: Reviews Complete, Docs/Not Needed

#171 eliminated the use of md5
  go.mod
  server/appservices/oauth2.go
  server/config/constants.go
  server/http/restapi/e2e_kv_test.go
  server/proxy/expand.go
  server/store/appkv.go
  server/store/appkv_test.go
  server/store/oauth2.go
  server/store/oauth2_test.go
  server/store/service.go
  server/store/service_test.go
Labels: 2: Editor Review, Docs/Needed

#177 Bump version to 0.5.0
  plugin.json
  server/manifest.go
Labels: 4: Reviews Complete, QA Review Done
