Repository mattermost/mattermost-plugin-apps, pull requests merged in 2021-08, with the labels that each got.

#225 remove md.MD
  apps/call.go
  apps/locations.go
  apps/permissions.go
  examples/go/hello-oauth2/hello.go
  examples/go/hello-webhooks/hello.go
  examples/go/hello/install.go
  examples/go/hello/send_survey.go
  examples/go/hello/submit_survey.go
  server/command/debug.go
  server/command/enable.go
  server/command/info.go
  server/command/list.go
  server/command/service.go
  server/command/uninstall.go
  server/httpin/dialog/install.go
  server/mocks/mock_proxy/mock_proxy.go
  server/proxy/enable.go
  server/proxy/install.go
  server/proxy/manifest.go
  server/proxy/service.go
  server/proxy/uninstall.go
  utils/md/markdown.go
  utils/utils.go
Labels: 2: Dev Review, AutoMerge

#224 [MM-36597] Add docker-compose development environment
  README.md
  build/custom.mk
  dev/README.md
  dev/docker-compose.override.yml
  dev/docker-compose.yml
  dev/node_app/.gitignore
  dev/node_app/nodemon.json
  dev/node_app/package-lock.json
  dev/node_app/package.json
  dev/node_app/src/app.ts
  dev/node_app/src/middleware/logger.ts
  dev/node_app/static/icon.png
  dev/node_app/tsconfig.json
Labels: 4: Reviews Complete

#217 [MM-3384] wrap manifest json data read error with better description
  server/command/install.go
Labels: 4: Reviews Complete

#231 refactored common service dependencies into config
  examples/go/hello-lambda/main.go
  examples/go/hello/http_hello/helloapp.go
  server/appservices/oauth2.go
  server/appservices/service.go
  server/appservices/subscriptions.go
  server/command/debug.go
  server/command/enable.go
  server/command/info.go
  server/command/install.go
  server/command/service.go
  server/command/uninstall.go
  server/config/service.go
  server/config/test_service.go
  server/httpin/dialog/dialog.go
  server/httpin/dialog/install.go
  server/httpin/gateway/gateway.go
  server/httpin/gateway/oauth2.go
  server/httpin/gateway/static.go
  server/httpin/gateway/webhook.go
  server/httpin/restapi/app.go
  server/httpin/restapi/bindings.go
  server/httpin/restapi/bindings_test.go
  server/httpin/restapi/call.go
  server/httpin/restapi/call_test.go
  server/httpin/restapi/kv_test.go
  server/httpin/restapi/restapi.go
  server/httpin/service.go
  server/httpout/service.go
  server/mmclient/client.go
  server/mmclient/http.go
  server/mmclient/rpc.go
  server/mocks/mock_config/mock_config.go
  server/mocks/mock_proxy/mock_proxy.go
  server/plugin.go
  server/proxy/bindings.go
  server/proxy/bindings_test.go
  server/proxy/enable.go
  server/proxy/expand.go
  server/proxy/install.go
  server/proxy/list.go
  server/proxy/oauth2.go
  server/proxy/proxy.go
  server/proxy/proxy_test.go
  server/proxy/service.go
  server/proxy/synchronize.go
  server/proxy/uninstall.go
  server/store/appkv.go
  server/store/apps.go
  server/store/manifest.go
  server/store/oauth2.go
  server/store/oauth2_test.go
  server/store/service.go
  server/store/service_test.go
  server/store/subscriptions.go
  server/store/subscriptions_test.go
Labels: 4: Reviews Complete

#234 Wait for Mattermost server to start before running e2e tests
  .circleci/config.yml
Labels: 4: Reviews Complete, Docs/Not Needed

#203 Filter bindings and commands on proxy
  server/proxy/bindings.go
  server/proxy/bindings_test.go
  server/proxy/proxy.go
  server/proxy/proxy_test.go
Labels: 4: Reviews Complete, Docs/Needed

#220 [MM-26812] Add bot-mention and bot leave/join subscriptions
  apps/subscription.go
  server/appservices/service.go
  server/appservices/subscriptions.go
  server/httpin/restapi/restapi.go
  server/httpin/restapi/subscribe.go
  server/mocks/mock_appservices/mock_appservices.go
  server/mocks/mock_proxy/mock_proxy.go
  server/plugin.go
  server/proxy/notify_test.go
  server/proxy/proxy.go
  server/proxy/service.go
  server/store/subscriptions.go
Labels: 4: Reviews Complete

#235 [MM-36622] Remove http-hello and update e2e tests
  .circleci/config.yml
  build/custom.mk
  e2e/cypress.json
  e2e/cypress/integration/bindings/channel_header_spec.ts
  examples/go/hello-world/manifest.json
  examples/go/hello/bindings.go
  examples/go/hello/builtin_hello/helloapp.go
  examples/go/hello/helloapp.go
  examples/go/hello/http_hello/functions.go
  examples/go/hello/http_hello/helloapp.go
  examples/go/hello/install.go
  examples/go/hello/send_survey.go
  examples/go/hello/submit_survey.go
  examples/go/hello/survey.go
  examples/go/hello/user_joined_channel.go
  server/plugin.go
Labels: 4: Reviews Complete

#237 [MM-36445] Changing elastic search docker version
  .circleci/config.yml
Labels: 4: Reviews Complete

#238 Add homepage_url to example app to fix CI
  examples/js/hello-world/app.js
Labels: 4: Reviews Complete

#222 Kubeless support
  apps/app.go
  apps/manifest.go
  cmd/appsctl/aws.go
  cmd/appsctl/kubeless.go
  cmd/appsctl/main.go
  cmd/appsctl/provision.go
  cmd/appsctl/terraform.go
  examples/js/hello-kubeless/Makefile
  examples/js/hello-kubeless/app.js
  examples/js/hello-kubeless/manifest.json
  examples/js/hello-kubeless/package.json
  go.mod
  go.sum
  public/hello.html
  server/command/install.go
  server/command/service.go
  server/config/service.go
  server/httpin/dialog/install.go
  server/httpin/restapi/app.go
  server/httpout/service.go
  server/mocks/mock_proxy/mock_proxy.go
  server/mocks/mock_store/mock_app.go
  server/mocks/mock_upstream/mock_upstream.go
  server/plugin.go
  server/proxy/bindings.go
  server/proxy/bindings_test.go
  server/proxy/form.go
  server/proxy/form_test.go
  server/proxy/install.go
  server/proxy/notify_test.go
  server/proxy/proxy.go
  server/proxy/proxy_test.go
  server/proxy/service.go
  server/store/apps.go
  server/store/manifest.go
  server/store/service.go
  server/store/service_test.go
  server/store/subscriptions_test.go
  upstream/serverless.go
  upstream/upaws/client.go
  upstream/upaws/client_lambda.go
  upstream/upaws/provision_data.go
  upstream/upaws/provision_data_test.go
  upstream/upaws/static.go
  upstream/upaws/upstream.go
  upstream/uphttp/static.go
  upstream/uphttp/upstream.go
  upstream/upkubeless/provision.go
  upstream/upkubeless/upstream.go
  upstream/upplugin/static.go
  upstream/upplugin/upstream.go
  upstream/upstream.go
  upstream/wrappers.go
  utils/path.go
  utils/utils.go
Labels: 1: PM Review, Awaiting Submitter Action, 3: QA Review, Docs/Needed

#239 Change selector for e2e test
  e2e/cypress/integration/bindings/channel_header_spec.ts
Labels: 4: Reviews Complete

#243 [MM-37242] Add comment explaining why /apps list is public
  server/command/list.go
Labels: 2: Dev Review, Docs/Not Needed

#227 Add localisation for Apps
  apps/context.go
  apps/expand.go
  server/proxy/expand.go
  utils/utils.go
Labels: 4: Reviews Complete, Docs/Done

#240 Remove usage of non-existent c.SourePluginId
  server/httpin/service.go
Labels: 4: Reviews Complete

#248 [MM-38155] Add recover handler for commands and HTTP requests
  server/command/service.go
  server/httpin/service.go
Labels: 4: Reviews Complete, Docs/Not Needed

#247 [MM-33770] Use permssion specific client to expands calls
  server/command/service.go
  server/httpin/dialog/install.go
  server/httpin/restapi/app.go
  server/mmclient/client.go
  server/mmclient/http.go
  server/mmclient/rpc.go
  server/proxy/expand.go
Labels: 4: Reviews Complete, Docs/Not Needed

#245 [MM-38099] Limit reads in API and command layer
  apps/manifest.go
  server/command/debug.go
  server/command/install.go
  server/httpin/restapi/kv.go
  server/httpin/restapi/kv_test.go
  server/httpin/restapi/oauth2.go
  server/httpin/restapi/oauth2_test.go
  server/httpout/service.go
  server/store/manifest.go
Labels: 4: Reviews Complete, Docs/Not Needed

#249 [MM-38190] [MM-38015] Don't try to set the bot icon in install process if request to it failed
  server/proxy/install.go
Labels: 4: Reviews Complete, Docs/Not Needed
