Repository mattermost/mattermost-plugin-apps, pull requests merged in 2021-06, with the labels that each got.

#194 Allow installation from Apps running in AWS directly
  cmd/appsctl/provision.go
  e2e/cypress/integration/bindings/channel_header_spec.ts
  server/command/install.go
  server/command/service.go
  server/mocks/mock_proxy/mock_proxy.go
  server/plugin.go
  server/proxy/bindings_test.go
  server/proxy/install.go
  server/proxy/list.go
  server/proxy/proxy_test.go
  server/proxy/service.go
  server/store/manifest.go
  server/store/service.go
  server/store/service_test.go
  server/store/subscriptions_test.go
  upstream/upaws/provision_app.go
Labels: Docs/Needed

#193 Implement feedback on AWS support
  cmd/appsctl/aws.go
  cmd/appsctl/main.go
  cmd/appsctl/provision.go
  e2e/cypress/integration/bindings/channel_header_spec.ts
  examples/go/hello-lambda/Makefile
  examples/go/hello-lambda/bindings.json
  examples/go/hello-lambda/main.go
  examples/go/hello-lambda/manifest-http.json
  examples/go/hello-lambda/manifest.json
  examples/go/hello/user_joined_channel.go
  server/command/debug.go
  server/command/info.go
  server/command/install.go
  server/command/list.go
  server/command/service.go
  server/command/uninstall.go
  server/mocks/mock_proxy/mock_proxy.go
  server/plugin.go
  server/proxy/bindings.go
  server/proxy/bindings_test.go
  server/proxy/expand.go
  server/proxy/install.go
  server/proxy/list.go
  server/proxy/proxy.go
  server/proxy/proxy_test.go
  server/proxy/service.go
  server/proxy/synchronize.go
  server/store/apps.go
  server/store/manifest.go
  server/store/service.go
  server/store/service_test.go
  server/store/subscriptions_test.go
  upstream/upaws/clean.go
  upstream/upaws/initialize.go
  upstream/upaws/provision_app.go
  upstream/upaws/provision_data.go
Labels: 4: Reviews Complete, Docs/Not Needed

#198 [MM-36056] Add modes info
  server/command/info.go
Labels: 4: Reviews Complete, Docs/Not Needed

#187 Remove CancelButton and SubmitOnCancel form properties
  apps/form.go
Labels: 4: Reviews Complete, Docs/Done

#184 Add label for hello-webhooks command bindings
  examples/go/hello-webhooks/bindings.json
Labels: 4: Reviews Complete, Docs/Not Needed

#190 Change homepage url to point to docs
  plugin.json
  server/manifest.go
Labels: 4: Reviews Complete

#199 [MM-36226] List type and status separately
  server/command/list.go
Labels: 4: Reviews Complete, Docs/Not Needed

#197 [MM-30595] Add support for relative icon path to bindings and forms
  apps/binding.go
  examples/go/hello-oauth2/bindings.json
  examples/go/hello-oauth2/configure_form.json
  examples/go/hello-oauth2/connect_form.json
  examples/go/hello-oauth2/send_form.json
  examples/go/hello-webhooks/bindings.json
  examples/go/hello-webhooks/info_form.json
  examples/go/hello-webhooks/send_form.json
  examples/go/hello-world/bindings.json
  examples/go/hello-world/send_form.json
  examples/js/hello-world/app.js
  server/config/config.go
  server/httpin/gateway/static.go
  server/proxy/bindings.go
  server/proxy/bindings_test.go
  server/proxy/expand.go
  server/proxy/install.go
  server/proxy/proxy.go
  server/utils/path.go
  server/utils/path_test.go
Labels: 4: Reviews Complete, Docs/Done

#196 [MM-34921] Add app icon suppport
  apps/app.go
  apps/manifest.go
  examples/go/hello-oauth2/manifest.json
  examples/go/hello-webhooks/manifest.json
  examples/go/hello-world/manifest.json
  examples/js/hello-world/app.js
  server/command/install.go
  server/httpin/dialog/install.go
  server/proxy/install.go
  server/proxy/list.go
  server/proxy/proxy.go
  upstream/upaws/client_s3.go
  upstream/upaws/static.go
  upstream/upaws/upstream.go
  upstream/upaws/upstream_test.go
  upstream/uphttp/static.go
  upstream/uphttp/upstream.go
  upstream/upstream.go
Labels: 4: Reviews Complete, Docs/Done

#200 [MM-36227] Delete manifest when uninstalling an app
  server/proxy/uninstall.go
Labels: 4: Reviews Complete, Docs/Not Needed

#201 [MM-35762] Clean call path before making a request
  server/proxy/proxy.go
  server/proxy/proxy_test.go
  upstream/uphttp/upstream.go
  utils/path.go
  utils/path_test.go
Labels: 4: Reviews Complete

#206 Fixed MM-36358, bad merge resulting in crash
  upstream/upaws/upstream.go
Labels: 4: Reviews Complete, Docs/Not Needed

#202 [MM-36302] Update autocomplete when configuration changes
  server/command/service.go
  server/plugin.go
Labels: 4: Reviews Complete

#205 Bump version to 0.7.0
  plugin.json
  server/manifest.go
Labels: 4: Reviews Complete

#192 Add markdown field constant
  apps/field.go
Labels: 4: Reviews Complete, Docs/Done
