Repository mattermost/mattermost-plugin-apps, pull requests merged in 2021-09, with the labels that each got.

#241 [MM-38047] Use mattermost-server/v6
  apps/app.go
  apps/context.go
  apps/mmclient/mattermost_client.go
  apps/mmclient/mattermost_client_pp.go
  apps/subscription.go
  build/manifest/main.go
  build/pluginctl/main.go
  examples/go/hello-webhooks/hello.go
  go.mod
  go.sum
  server/appservices/service.go
  server/command/debug.go
  server/command/enable.go
  server/command/info.go
  server/command/install.go
  server/command/list.go
  server/command/service.go
  server/command/uninstall.go
  server/config/config.go
  server/config/mattermost_config_service.go
  server/config/service.go
  server/config/test_service.go
  server/httpin/dialog/dialog.go
  server/httpin/dialog/install.go
  server/httpin/restapi/call_test.go
  server/httpin/restapi/e2e_kv_test.go
  server/httpin/restapi/e2e_subscribe_test.go
  server/httpin/restapi/kv_test.go
  server/httpin/restapi/main_test.go
  server/httpin/restapi/restapitestlib.go
  server/httpin/service.go
  server/httpout/service.go
  server/main.go
  server/manifest.go
  server/mmclient/client.go
  server/mmclient/http.go
  server/mmclient/rpc.go
  server/mocks/mock_config/mock_config.go
  server/mocks/mock_proxy/mock_proxy.go
  server/plugin.go
  server/proxy/bindings.go
  server/proxy/bindings_test.go
  server/proxy/expand.go
  server/proxy/install.go
  server/proxy/list.go
  server/proxy/notify_test.go
  server/proxy/proxy.go
  server/proxy/proxy_test.go
  server/proxy/service.go
  server/store/oauth2_test.go
  server/store/service.go
  server/store/subscriptions_test.go
  utils/utils.go
Labels: 4: Reviews Complete, Docs/Not Needed

#253 Broadcast websocket message when plugin is enabled/disabled
  server/config/config.go
  server/config/constants.go
  server/httpin/restapi/ping.go
  server/httpin/restapi/restapi.go
  server/plugin.go
  server/plugin_test.go
  server/proxy/bindings.go
Labels: 3: QA Review, Docs/Not Needed

#256 [MM-38242] Directly use local http port to access Mattermost server from Apps plugin
  server/config/config.go
  server/mmclient/http.go
Labels: 4: Reviews Complete, Docs/Not Needed

#264 Fixed E2E test
  server/plugin_test.go
Labels: 4: Reviews Complete, Docs/Not Needed

#230 [MM-37324] Add telemetry
  build/custom.mk
  server/config/service.go
  server/config/test_service.go
  server/httpin/restapi/call.go
  server/mocks/mock_config/mock_config.go
  server/plugin.go
  server/proxy/install.go
  server/proxy/oauth2.go
  server/proxy/uninstall.go
  server/telemetry/telemetry.go
Labels: 3: QA Review, Docs/Needed

#251 OpenFaaS part 2: convert command and dialog to builtin
  dev/README.md
  e2e/cypress/integration/bindings/channel_header_spec.ts
  examples/go/hello-lifecycle/hello.go
  go.mod
  server/builtin/app.go
  server/builtin/bindings.go
  server/builtin/debug.go
  server/builtin/disable.go
  server/builtin/enable.go
  server/builtin/info.go
  server/builtin/install.go
  server/builtin/install_consent.go
  server/builtin/install_marketplace.go
  server/builtin/install_s3.go
  server/builtin/install_url.go
  server/builtin/list.go
  server/builtin/uninstall.go
  server/builtin/utils.go
  server/command/debug.go
  server/command/enable.go
  server/command/info.go
  server/command/install.go
  server/command/list.go
  server/command/service.go
  server/command/uninstall.go
  server/httpin/dialog/dialog.go
  server/httpin/dialog/install.go
  server/plugin.go
  server/proxy/expand.go
  server/proxy/incoming.go
  server/proxy/install.go
  upstream/upaws/aws.go
  upstream/upaws/client.go
  upstream/upaws/client_s3.go
  upstream/upaws/provision_data.go
  upstream/upaws/upstream.go
Labels: 4: Reviews Complete

#266 Fix bad merge
  server/plugin.go
  server/plugin_test.go
Labels: 4: Reviews Complete, Docs/Not Needed

#263 MM-37748: Added debug logging for how the cloud mode is detected
  server/config/config.go
  server/config/service.go
Labels: 4: Reviews Complete, Docs/Not Needed

#188 [MM35712] MM Apps - Invalidate bindings on oAuth disconnect
  examples/go/hello-oauth2/bindings.json
  examples/go/hello-oauth2/disconnect_form.json
  examples/go/hello-oauth2/hello.go
  examples/go/hello-oauth2/manifest.json
  server/appservices/oauth2.go
  server/appservices/service.go
  server/mocks/mock_appservices/mock_appservices.go
  server/proxy/oauth2.go
Labels: 2: Dev Review, QA Review Done, Docs/Needed
