Repository mattermost/mattermost-plugin-apps, pull requests merged in 2021-03, with the labels that each got.

#83 Add refresh websocket event on app install
  server/api/constants.go
  server/api/impl/admin/install.go
Labels: 2: Dev Review

#80 Do not omit type in JSON
  apps/call.go
Labels: 2: Dev Review

#53 [MM-31782] static asset proxy
  apps/app.go
  go.mod
  go.sum
  server/api/constants.go
  server/api/impl/aws/aws_keys.go
  server/api/impl/aws/provision_app.go
  server/api/impl/aws/s3.go
  server/api/impl/aws/service.go
  server/api/impl/proxy/asset.go
  server/api/proxy.go
  server/http/restapi/asset.go
  server/http/restapi/restapi.go
Labels: 2: Dev Review

#87 [MM-33399] Add MattermostSiteURL to Context for slash command
  apps/context.go
Labels: 4: Reviews Complete

#82 Add user agent to call context
  apps/context.go
  server/api/constants.go
  server/http/restapi/bindings.go
Labels: 4: Reviews Complete

#86 [MM-33377] Move AWS invoke credentials to env variables
  README.md
  plugin.json
  server/api/config.go
  server/api/impl/aws/service.go
  server/api/impl/configurator/configurator.go
  server/manifest.go
  server/plugin.go
Labels: 4: Reviews Complete

#78 [MM-33177] Simplify app sync
  assets/apps.json
  server/api/impl/admin/provision.go
  server/api/impl/admin/synchronization_test.go
  server/api/impl/admin/synchronize.go
  server/api/impl/store/apps.go
Labels: 4: Reviews Complete

#88 [MM-33128] Require Enable OAuth 2.0 Service Provider to run commands
  server/command/service.go
Labels: 4: Reviews Complete

#90 [MM-33468] Properly marshal call into JSON body for lambda requests
  server/api/impl/upstream/upawslambda/upstream.go
Labels: 4: Reviews Complete

#89 [MM-33404] Disable debug slash command and builtIn apps in production
  go.mod
  go.sum
  server/command/main.go
  server/command/service.go
  server/manifest.go
  server/plugin.go
Labels: 4: Reviews Complete

#92 [MM-33340] Add e2e tests to CI
  .circleci/config.yml
  .gitignore
  Makefile
  server/http/restapi/restapitestlib.go
Labels: 4: Reviews Complete

#96 E2E follow up fixes
  .circleci/config.yml
  .gitignore
  Makefile
  server/http/restapi/restapitestlib.go
  server/plugin.go
Labels: 4: Reviews Complete

#91 Change call type submit and call response ok to not be empty strings
  apps/call.go
  server/examples/go/hello/builtin_hello/helloapp.go
  server/examples/go/hello/http_hello/functions.go
  server/examples/go/hello/install.go
  server/http/restapi/call.go
Labels: 4: Reviews Complete, Do Not Merge

#94 Extract Call request struct from Call struct
  apps/call.go
  apps/call_test.go
  server/api/impl/admin/install.go
  server/api/impl/admin/synchronize.go
  server/api/impl/proxy/bindings.go
  server/api/impl/proxy/proxy.go
  server/api/impl/upstream/upawslambda/upstream.go
  server/api/impl/upstream/uphttp/upstream.go
  server/api/impl/upstream/wrappers.go
  server/api/mock_api/mock_proxy.go
  server/api/proxy.go
  server/api/upstream.go
  server/examples/go/hello/bindings.go
  server/examples/go/hello/builtin_hello/helloapp.go
  server/examples/go/hello/helloapp.go
  server/examples/go/hello/http_hello/functions.go
  server/examples/go/hello/http_hello/helloapp.go
  server/examples/go/hello/install.go
  server/examples/go/hello/send_survey.go
  server/examples/go/hello/submit_survey.go
  server/examples/go/hello/survey.go
  server/examples/go/hello/user_joined_channel.go
  server/http/restapi/call.go
Labels: 4: Reviews Complete

#97 Customize base commands and sub commands
  Makefile
  server/api/impl/proxy/bindings.go
  server/api/impl/proxy/bindings_test.go
  server/api/mock_api/mock_app_store.go
  server/api/mock_api/mock_config.go
  server/api/mock_api/mock_proxy.go
  server/api/mock_api/mock_store.go
  server/api/mock_api/mock_upstream.go
  server/examples/go/hello/bindings.go
Labels: 4: Reviews Complete, Awaiting Submitter Action

#102 Embed directly instead of using pointers
  server/api/config.go
  server/api/impl/configurator/configurator.go
  server/api/impl/configurator/test_service.go
  server/api/impl/store/subscriptions_test.go
  server/api/mock_api/mock_config.go
  server/main.go
  server/plugin.go
Labels: 4: Reviews Complete

#99 Remove type from call and consider type on path for helloapp
  apps/call.go
  server/examples/go/hello/builtin_hello/helloapp.go
  server/examples/go/hello/http_hello/functions.go
  server/examples/go/hello/http_hello/helloapp.go
  server/examples/go/hello/install.go
  server/examples/go/hello/send_survey.go
Labels: 2: Dev Review

#100 Docs, take i+1
  apps/app.go
  apps/aws.go
  apps/binding.go
  apps/call.go
  apps/call_test.go
  apps/context.go
  apps/expand.go
  apps/field.go
  apps/form.go
  apps/manifest.go
  apps/package.go
  apps/permissions.go
  apps/subscription.go
  assets/example-aws-hello.json
  awsclient/generate_names.go
  awsclient/s3.go
  cmd/appsctl/provision.go
  cmd/appsctl/provision_app.go
  docs/00-toc.md
  docs/01-anatomy-hello.md
  docs/02-example-post-menu.md
  docs/03-example-interactivity.md
  docs/05-using-mattermost-api.md
  docs/06-using-3rdparty-api.md
  docs/07-lifecycle.md
  go.mod
  go.sum
  server/api/constants.go
  server/api/impl/proxy/asset.go
  server/api/impl/proxy/bindings_test.go
  server/api/impl/proxy/enable.go
  server/api/impl/proxy/expand.go
  server/api/impl/proxy/proxy.go
  server/api/impl/store/manifest.go
  server/api/impl/store/subscriptions_test.go
  server/api/impl/upstream/upawslambda/upstream.go
  server/api/impl/upstream/upawslambda/upstream_test.go
  server/command/list.go
  server/examples/go/hello/bindings.go
  server/examples/go/hello/builtin_hello/helloapp.go
  server/examples/go/hello/http_hello/helloapp.go
  server/examples/go/hello/send_survey.go
  server/examples/go/helloworld/bindings.json
  server/examples/go/helloworld/hello.go
  server/examples/go/helloworld/icon.png
  server/examples/go/helloworld/manifest.json
  server/examples/go/helloworld/send_form.json
  server/examples/js/aws_hello/helloapp.go
  server/http/dialog/install.go
  server/http/restapi/call.go
  server/plugin.go
Labels: 2: Dev Review

#106 fixed mocks
  Makefile
  server/mocks/mock_store/mock_app.go
  server/proxy/bindings_test.go
Labels: 4: Reviews Complete

#108 Fix flaky bindings test
  server/proxy/bindings_test.go
Labels: 4: Reviews Complete

#93 Add generate-terraform-data command
  README.md
  apps/app.go
  apps/aws.go
  apps/manifest.go
  aws/client.go
  aws/iam.go
  aws/lambda.go
  aws/provision_app.go
  aws/provision_data.go
  aws/provision_data_test.go
  aws/s3.go
  cmd/appsctl/generate_terraform.go
  cmd/appsctl/main.go
  cmd/appsctl/provision.go
  cmd/appsctl/provision_app.go
  server/plugin.go
  server/proxy/service.go
  server/store/manifest.go
  server/upstream/upawslambda/upstream.go
  server/utils/utils.go
  tests/test-bundle.zip
Labels: 4: Reviews Complete

#105 Fix expand, uninstall and send survey
  server/command/uninstall.go
  server/examples/go/hello/send_survey.go
  server/proxy/expand.go
  server/proxy/install.go
  server/proxy/service.go
  server/proxy/uninstall.go
  server/store/apps.go
Labels: 2: Dev Review

#110 docs fixes
  apps/package.go
Labels: 4: Reviews Complete

#109 Updated helloworld to work with call type changes
  docs/01-anatomy-hello.md
  server/examples/go/helloworld/hello.go
Labels: 4: Reviews Complete

#113 MM-31118: 3rd party OAuth2 support
  Makefile
  apps/call.go
  apps/context.go
  apps/mmclient/mattermost_client.go
  apps/mmclient/mattermost_client_pp.go
  docs/02-example-post-menu.md
  go.mod
  go.sum
  server/appservices/kv.go
  server/appservices/kv_test.go
  server/command/debug.go
  server/config/config.go
  server/config/constants.go
  server/config/test_service.go
  server/examples/go/hello-3rdparty/bindings.json
  server/examples/go/hello-3rdparty/configure_form.json
  server/examples/go/hello-3rdparty/connect_form.json
  server/examples/go/hello-3rdparty/hello.go
  server/examples/go/hello-3rdparty/icon.png
  server/examples/go/hello-3rdparty/manifest.json
  server/examples/go/hello-3rdparty/send_form.json
  server/http/dialog/dialog.go
  server/http/dialog/install.go
  server/http/gateway/gateway.go
  server/http/gateway/oauth2.go
  server/http/gateway/static.go
  server/http/restapi/bindings.go
  server/http/restapi/call.go
  server/http/restapi/kv.go
  server/http/restapi/kv_test.go
  server/http/restapi/marketplace.go
  server/http/restapi/restapi.go
  server/http/restapi/restapi_test.go
  server/mocks/mock_appservices/mock_appservices.go
  server/mocks/mock_config/mock_config.go
  server/mocks/mock_proxy/mock_proxy.go
  server/mocks/mock_store/mock_app.go
  server/mocks/mock_upstream/mock_upstream.go
  server/plugin.go
  server/proxy/bindings_test.go
  server/proxy/install.go
  server/proxy/manifest.go
  server/proxy/proxy.go
  server/proxy/service.go
  server/utils/httputils/utils.go
Labels: 4: Reviews Complete

#116 Fix debug add manifest command errors
  server/command/debug.go
Labels: 4: Reviews Complete

#120 Remove io/ioutil
  apps/mmclient/mattermost_client_pp.go
  aws/lambda.go
  aws/provision_data.go
  server/examples/go/hello/builtin_hello/helloapp.go
  server/http/restapi/restapitestlib.go
  server/proxy/bindings_test.go
  server/store/manifest.go
  server/utils/httputils/limited_readcloser_test.go
  server/utils/httputils/utils.go
Labels: 4: Reviews Complete

#122 [MM-34462] Fix /apps info command
  Makefile
Labels: 4: Reviews Complete
