Repository mattermost/mattermost-plugin-apps, pull requests merged in 2021-11, with the labels that each got.

#281 MM-39776 moved Build variables to config
  Makefile
  build/custom.mk
  server/builtin/app.go
  server/builtin/info.go
  server/config/config.go
  server/config/config_test.go
  server/config/service.go
  server/main.go
  server/plugin.go
  server/plugin_test.go
  server/store/apps.go
  server/store/manifest.go
Labels: 2: Dev Review, QA Review Done

#278 Added `/apps debug kv` command
  assets/i18n/active.en.json
  assets/i18n/active.es.json
  server/appservices/kv.go
  server/appservices/service.go
  server/builtin/app.go
  server/builtin/bindings.go
  server/builtin/debug.go
  server/builtin/debug_bindings.go
  server/builtin/debug_kv_clean.go
  server/builtin/debug_kv_edit.go
  server/builtin/debug_kv_edit_modal.go
  server/builtin/debug_kv_info.go
  server/builtin/debug_kv_list.go
  server/builtin/disable.go
  server/builtin/enable.go
  server/builtin/install.go
  server/builtin/install_consent.go
  server/builtin/list.go
  server/builtin/uninstall.go
  server/builtin/utils.go
  server/mocks/mock_appservices/mock_appservices.go
  server/mocks/mock_store/mock_appkv.go
  server/plugin.go
  server/proxy/uninstall.go
  server/store/appkv.go
  server/store/oauth2.go
  server/store/service.go
  server/store/service_test.go
Labels: 2: Dev Review

#287 Fixed /apps debug kv clean, added create
  server/builtin/app.go
  server/builtin/debug.go
  server/builtin/debug_kv_clean.go
  server/builtin/debug_kv_create.go
Labels: 4: Reviews Complete

#283 [MM-39731] Don't request bindings from app that doen't have granted locations
  server/proxy/bindings.go
  server/proxy/bindings_test.go
Labels: 4: Reviews Complete, Docs/Not Needed

#289 Fixed `/apps debug clean` call
  server/builtin/debug_clean.go
  server/builtin/debug_kv_clean.go
Labels: 4: Reviews Complete

#280 [MM-39311] Pass session token to call made by the buitin app
  server/builtin/app.go
  server/builtin/debug_bindings.go
  server/builtin/debug_clean.go
  server/builtin/debug_kv_edit.go
  server/builtin/debug_kv_edit_modal.go
  server/builtin/debug_kv_info.go
  server/builtin/disable.go
  server/builtin/enable.go
  server/builtin/info.go
  server/builtin/install.go
  server/builtin/install_consent.go
  server/builtin/list.go
  server/builtin/uninstall.go
  server/builtin/utils.go
  server/proxy/expand.go
  server/proxy/incoming.go
  upstream/upkubeless/upstream.go
Labels: 3: QA Review, Docs/Not Needed

#284 [MM-39827] Remove AdminAccessToken & PermissionActAsAdmin
  apps/appclient/mattermost_client.go
  apps/context.go
  apps/expand.go
  apps/permissions.go
  examples/go/hello-webhooks/hello.go
  examples/go/hello-webhooks/manifest.json
  server/builtin/app.go
  server/builtin/debug_bindings.go
  server/builtin/install_consent.go
  server/httpin/restapi/call_test.go
  server/proxy/enable.go
  server/proxy/expand.go
  server/proxy/incoming.go
  server/proxy/install.go
  server/proxy/uninstall.go
Labels: 4: Reviews Complete, Docs/Needed, Breaking Change

#288 MM-39798: expand channel and team membership
  Makefile
  apps/context.go
  apps/expand.go
  server/mmclient/client.go
  server/mmclient/http.go
  server/mmclient/rpc.go
  server/mocks/mock_mmclient/mock_mmclient.go
  server/proxy/expand.go
  server/proxy/expand_test.go
  server/proxy/service.go
Labels: 4: Reviews Complete, Docs/Needed

#290 Debug fixes and improvements for gcal
  apps/context.go
  assets/i18n/active.en.json
  server/builtin/debug.go
  server/builtin/debug_bindings.go
  server/builtin/debug_kv_clean.go
  server/builtin/debug_kv_edit.go
  server/builtin/debug_kv_list.go
  server/builtin/install_consent.go
  server/proxy/expand.go
Labels: 3: QA Review, 4: Reviews Complete, Docs/Needed

#292 [MM-40055] Build tooling update
  .circleci/config.yml
  Makefile
  build/custom.mk
  build/manifest/main.go
  build/pluginctl/main.go
  build/setup.mk
  plugin.go
  plugin.json
  server/main.go
  server/manifest.go
Labels: 4: Reviews Complete, Docs/Not Needed

#293 [MM-40102] Correctly enable apps plugin for E2E tests
  server/httpin/restapi/e2e_kv_test.go
  server/httpin/restapi/e2e_subscribe_test.go
  server/httpin/restapi/restapitestlib.go
Labels: 2: Dev Review, Docs/Not Needed

#295 Fix subpath for local requests
  server/config/config.go
  server/httpin/restapi/restapitestlib.go
  server/plugin_test.go
Labels: 4: Reviews Complete, Docs/Not Needed
