Repository mattermost/mattermost-plugin-apps, pull requests merged in 2021-02, with the labels that each got.

#58 Fix panic that happens on server restart
  server/plugin.go
Labels: 4: Reviews Complete

#59 Add missing details for get bindings context
  server/api/impl/proxy/bindings.go
  server/http/restapi/bindings.go
Labels: 4: Reviews Complete

#57 [MM-32476] Apps in the Marketplace
  server/api/constants.go
  server/http/restapi/marketplace.go
  server/http/restapi/marketplace_test.go
  server/http/restapi/restapi.go
Labels: 4: Reviews Complete

#60 Fix goimports prefix
  .golangci.yml
  apps/mmclient/mattermost_client.go
  apps/mmclient/mattermost_client_pp.go
  server/api/impl/admin/admin.go
  server/api/impl/admin/install.go
  server/api/impl/appservices/kv.go
  server/api/impl/configurator/test_service.go
  server/api/impl/proxy/bindings.go
  server/api/impl/proxy/bindings_test.go
  server/api/impl/proxy/expand.go
  server/api/impl/proxy/manifest.go
  server/api/impl/store/store.go
  server/api/impl/store/subscriptions.go
  server/api/upstream.go
  server/http/dialog/dialog.go
  server/http/restapi/marketplace_test.go
  server/http/restapi/restapitestlib.go
  server/http/restapi/subscribe.go
  server/utils/httputils/limited_readcloser_test.go
Labels: 4: Reviews Complete

#61 Drop CODEOWNERS file
  CODEOWNERS
Labels: 4: Reviews Complete

#46 Add apps synchronization
  apps/app.go
  assets/apps.json
  server/api/admin.go
  server/api/aws.go
  server/api/config.go
  server/api/impl/admin/admin.go
  server/api/impl/admin/install.go
  server/api/impl/admin/list.go
  server/api/impl/admin/provision.go
  server/api/impl/admin/synchronize.go
  server/api/impl/appservices/subscriptions.go
  server/api/impl/aws/lambda.go
  server/api/impl/aws/provision_app.go
  server/api/impl/aws/s3.go
  server/api/impl/aws/service.go
  server/api/impl/proxy/bindings.go
  server/api/impl/proxy/proxy.go
  server/api/impl/store/apps.go
  server/api/impl/store/manifests.go
  server/api/impl/store/store.go
  server/api/impl/store/subscriptions.go
  server/api/impl/store/subscriptions_test.go
  server/api/impl/upstream/upawslambda/upstream.go
  server/api/mock_api/mock_appservices.go
  server/api/mock_api/mock_proxy.go
  server/api/store.go
  server/command/install.go
  server/command/main.go
  server/examples/go/hello/builtin_hello/helloapp.go
  server/examples/go/hello/install.go
  server/examples/js/aws_hello/helloapp.go
  server/http/restapi/marketplace.go
  server/http/restapi/marketplace_test.go
  server/http/restapi/restapi_test.go
  server/plugin.go
Labels: 4: Reviews Complete, Awaiting Submitter Action

#65 [MM-32862] Sanitized app version and id for function name
  apps/app.go
  server/api/impl/aws/provision_app.go
Labels: 4: Reviews Complete

#64 Reduced the linked image size
  server/api/mock_api/mock_appservices.go
  server/api/mock_api/mock_proxy.go
  server/http/restapi/restapitestlib.go
Labels: 4: Reviews Complete

#70 [MM-32910] Fix app store
  server/api/config.go
  server/api/impl/store/apps.go
Labels: 2: Dev Review

#56 Rework embedded forms
  apps/binding.go
  apps/constants.go
  server/api/constants.go
  server/examples/go/hello/helloapp.go
  server/examples/go/hello/http_hello/functions.go
  server/examples/go/hello/http_hello/helloapp.go
  server/examples/go/hello/send_survey.go
  server/examples/go/hello/submit_survey.go
Labels: 4: Reviews Complete

#68 [MM-32902] Fix default s3 bucket name
  server/api/impl/aws/service.go
Labels: 2: Dev Review

#69 Respect bundle path when reading apps.json
  server/api/impl/admin/synchronize.go
Labels: 4: Reviews Complete

#73 [MM-33081] Don't modify app passed to store
  server/api/impl/store/apps.go
Labels: 4: Reviews Complete

#62 Provision static assets
  server/api/impl/aws/aws_keys.go
  server/api/impl/aws/provision_app.go
  server/api/impl/aws/s3.go
  server/api/impl/aws/service.go
Labels: 2: Dev Review

#71 [MM-33078] Add app status to /apps list
  server/api/impl/admin/list.go
Labels: 4: Reviews Complete

#76 [MM-33093] Improve handling when manifest is not found on S3
  server/api/impl/admin/synchronize.go
Labels: 4: Reviews Complete

#75 [MM-30046] Add /uninstall command
  server/api/admin.go
  server/api/impl/admin/synchronize.go
  server/command/main.go
  server/command/uninstall.go
Labels: 2: Dev Review

#66 Fix Install flow
  server/api/admin.go
  server/api/impl/admin/list.go
  server/api/impl/admin/provision.go
  server/api/impl/store/apps.go
  server/api/impl/store/manifests.go
  server/api/store.go
  server/command/install.go
  server/command/main.go
Labels: 4: Reviews Complete

#79 Fix bad merge
  server/api/impl/store/apps.go
Labels: 4: Reviews Complete

#67 [MM-32702] Introduce appsctl
  README.md
  assets/apps.json
  cmd/appsctl/completion.go
  cmd/appsctl/log.go
  cmd/appsctl/main.go
  cmd/appsctl/provision.go
  go.mod
  go.sum
  server/api/aws.go
  server/api/impl/aws/provision_app.go
  server/api/impl/aws/s3.go
  server/api/impl/aws/service.go
  server/command/install.go
  server/command/main.go
Labels: 4: Reviews Complete

#74 [MM-33083] Use HTTP request like payload to invoke lambda
  server/api/aws.go
  server/api/impl/aws/lambda.go
  server/api/impl/upstream/upawslambda/upstream.go
Labels: 4: Reviews Complete

#77 [MM-31508] Rename URL to Path in Call
  apps/app.go
  apps/call.go
  server/api/impl/admin/synchronize.go
  server/api/impl/proxy/bindings_test.go
  server/api/impl/upstream/upawslambda/upstream.go
  server/api/impl/upstream/uphttp/upstream.go
  server/examples/go/hello/builtin_hello/helloapp.go
  server/examples/go/hello/install.go
  server/examples/js/aws_hello/helloapp.go
Labels: 4: Reviews Complete
