Repository mattermost/mattermost-plugin-apps, pull requests merged in 2021-05, with the labels that each got.

#178 Change description text
  plugin.json
  server/manifest.go
Labels: 4: Reviews Complete

#175 include the expanded oauth2 user on oauth2complete
  apps/manifest.go
Labels: 4: Reviews Complete, Docs/Needed

#179 update inbucket to use mattermost/inbucket:release-1.2.0
  .circleci/config.yml
Labels: 4: Reviews Complete

#173 MM-35063: fixed static path traversal vulnerability
  server/http/gateway/static.go
  server/http/gateway/static_test.go
Labels: 4: Reviews Complete, Docs/Not Needed

#166 [MM-35184] Pass app ID as positional argument to install command
  e2e/cypress/integration/bindings/channel_header_spec.ts
  server/command/install.go
  server/command/main.go
Labels: 4: Reviews Complete, Docs/Done

#180 MM-35389: Use the server's httpservice for outgoing http
  .gitignore
  apps/locations.go
  server/command/debug.go
  server/command/install.go
  server/command/main.go
  server/command/service.go
  server/config/config.go
  server/config/mattermost_config_service.go
  server/config/service.go
  server/config/test_service.go
  server/httpin/dialog/dialog.go
  server/httpin/dialog/install.go
  server/httpin/gateway/gateway.go
  server/httpin/gateway/oauth2.go
  server/httpin/gateway/static.go
  server/httpin/gateway/static_test.go
  server/httpin/gateway/webhook.go
  server/httpin/restapi/bindings.go
  server/httpin/restapi/bindings_test.go
  server/httpin/restapi/call.go
  server/httpin/restapi/call_test.go
  server/httpin/restapi/e2e_kv_test.go
  server/httpin/restapi/e2e_subscribe_test.go
  server/httpin/restapi/get_ids.go
  server/httpin/restapi/kv.go
  server/httpin/restapi/kv_test.go
  server/httpin/restapi/main_test.go
  server/httpin/restapi/marketplace.go
  server/httpin/restapi/oauth2.go
  server/httpin/restapi/restapi.go
  server/httpin/restapi/restapitestlib.go
  server/httpin/restapi/subscribe.go
  server/httpin/service.go
  server/httpout/service.go
  server/mocks/mock_config/mock_config.go
  server/plugin.go
  server/proxy/expand.go
  server/proxy/proxy.go
  server/proxy/service.go
  server/store/manifest.go
  server/upstream/uphttp/upstream.go
  server/utils/httputils/utils.go
Labels: 1: PM Review, 2: Dev Review, Docs/Needed

#143 Set minimum version
  .circleci/config.yml
  go.mod
  go.sum
  plugin.json
  server/manifest.go
Labels: 4: Reviews Complete, Docs/Not Needed

#183 removed webapp
  Makefile
  webapp/.eslintrc.json
  webapp/.gitignore
  webapp/.npmrc
  webapp/babel.config.js
  webapp/i18n/en.json
  webapp/package-lock.json
  webapp/package.json
  webapp/src/index.js
  webapp/src/manifest.js
  webapp/src/manifest.test.js
  webapp/tests/i18n_mock.json
  webapp/tests/setup.js
  webapp/tsconfig.json
  webapp/webpack.config.js
Labels: 4: Reviews Complete, Docs/Not Needed

#189 Bump version to 0.6.0
  plugin.json
  server/manifest.go
Labels: 4: Reviews Complete

#174 Add js hello-world example
  examples/go/hello-world/bindings.json
  examples/go/hello-world/hello.go
  examples/go/hello-world/icon.png
  examples/go/hello-world/manifest.json
  examples/go/hello-world/send_form.json
  examples/go/helloapp.go
  examples/js/aws_hello/manifest.json
  examples/js/aws_hello/on_activate/index.js
  examples/js/hello-world/.gitignore
  examples/js/hello-world/app.js
  examples/js/hello-world/icon.png
  examples/js/hello-world/package-lock.json
  examples/js/hello-world/package.json
Labels: 4: Reviews Complete, Do Not Merge/Awaiting PR, Docs/Done

#186 style: small refactor is bindings.go
  server/proxy/bindings.go
Labels: 4: Reviews Complete, Docs/Not Needed
