Repository mattermost/mattermost-plugin-apps, pull requests merged in 2022-10, with the labels that each got.

#362 Move /examples and /dev to new mattermost-app-examples repository
  README.md
  build/custom.mk
  dev/README.md
  dev/docker-compose.override.yml
  dev/docker-compose.yml
  dev/node_app/.gitignore
  dev/node_app/nodemon.json
  dev/node_app/package-lock.json
  dev/node_app/package.json
  dev/node_app/src/app.ts
  dev/node_app/src/middleware/logger.ts
  dev/node_app/tsconfig.json
  dev/short_names.md
  examples/README.md
  examples/go/hello-jwt/hello.go
  examples/go/hello-lifecycle/hello.go
  examples/go/hello-lifecycle/manifest.json
  examples/go/hello-oauth2/hello.go
  examples/go/hello-oauth2/icon.png
  examples/go/hello-serverless/.gitignore
  examples/go/hello-serverless/DEMO.md
  examples/go/hello-serverless/Makefile
  examples/go/hello-serverless/function/go.mod
  examples/go/hello-serverless/function/go.sum
  examples/go/hello-serverless/function/handler.go
  examples/go/hello-serverless/hello/handler.go
  examples/go/hello-serverless/hello/static/icon.png
  examples/go/hello-serverless/hello/static/manifest.json
  examples/go/hello-serverless/hello/static/test.txt
  examples/go/hello-serverless/main.go
  examples/go/hello-serverless/openfaas.yml
  examples/go/hello-webhooks/hello.go
  examples/go/hello-webhooks/icon.png
  examples/go/hello-world/icon.png
  examples/goapp/expand/static/icon.png
  examples/goapp/hello-world/static/icon.png
  examples/js/aws_hello/manifest.json
  examples/js/aws_hello/on_activate/index.js
  examples/js/hello-world/.gitignore
  examples/js/hello-world/app.js
  examples/js/hello-world/icon.png
  examples/js/hello-world/package-lock.json
  examples/js/hello-world/package.json
  examples/python/README.md
  examples/python/requirements.txt
  examples/python/src/hello-world.py
  examples/python/src/static/icon.png
  go.mod
  goapp/expand/app.go
  goapp/expand/echo.go
  goapp/expand/expand_fields.go
  goapp/expand/notify.gogo
  goapp/expand/static/icon.png
  goapp/expand/user_action.go
  goapp/hello-world/app.go
  goapp/hello-world/static/icon.png
  test/hello-world/hello.go
  test/hello-world/icon.png
Labels: 2: Dev Review

#373 [MM-47962] Skip TestRESTAPI/notify/user_left_team
  test/restapitest/notify_user_left_team.go
Labels: 4: Reviews Complete

#371 Updated CodeQL to use latest version
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: 4: Reviews Complete, Docs/Not Needed

#370 Fix e2e tests for webapp master branch
  .circleci/config.yml
  test/e2e/cypress/support/index.ts
Labels: 4: Reviews Complete
