Repository mattermost/mattermost-plugin-apps, pull requests merged in 2022-03, with the labels that each got.

#302 Update to go1.17
  go.mod
  server/httpin/restapi/e2e_kv_test.go
  server/httpin/restapi/e2e_subscribe_test.go
  server/httpin/restapi/main_test.go
  server/httpin/restapi/restapitestlib.go
Labels: 4: Reviews Complete, Docs/Not Needed

#299 [MM-39951] Guard ensureBot with mutex
  go.mod
  go.sum
  server/plugin_test.go
Labels: 4: Reviews Complete, Docs/Not Needed

#298 [MM-39510] Don't provide channel, team and post ID by default in call context
  .circleci/config.yml
  apps/appclient/mattermost_client.go
  apps/context.go
  apps/expand.go
  dev/node_app/src/app.ts
  examples/go/hello-jwt/hello.go
  examples/go/hello-lifecycle/hello.go
  examples/go/hello-serverless/function/handler.go
  examples/go/hello-world/hello.go
  examples/js/hello-world/app.js
  server/builtin/app.go
  server/builtin/bindings.go
  server/builtin/debug_kv_clean.go
  server/builtin/debug_kv_create.go
  server/builtin/debug_kv_edit.go
  server/builtin/debug_session_list.go
  server/httpin/restapi/call_test.go
  server/httpin/restapi/restapitestlib.go
  server/incoming/request.go
  server/proxy/enable.go
  server/proxy/expand.go
  server/proxy/expand_test.go
  upstream/uphttp/upstream.go
  upstream/upplugin/upstream.go
Labels: 4: Reviews Complete, Docs/Needed, Breaking Change, QA Deferred

#304 [MM-42523] Add SelectedField and Query properties to CallRequest
  apps/call_request.go
Labels: 3: QA Review

#310 Store app and manifest KV even when SHA did not change
  server/store/apps.go
  server/store/manifest.go
Labels: 3: QA Review, 4: Reviews Complete

#305 force /cloud test serversand community-xxx to developer mode
  assets/i18n/active.en.json
  assets/i18n/active.es.json
  server/builtin/info.go
  server/builtin/install.go
  server/config/config.go
  server/plugin.go
  server/proxy/service.go
Labels: 3: QA Review, 4: Reviews Complete, Docs/Not Needed

#311 bundle ServiceNow 0.3.2 on Mattermost Cloud
  .circleci/config.yml
  assets/i18n/active.en.json
  assets/manifests.json
  go.mod
  go.sum
  server/builtin/info.go
Labels: 2: Dev Review, 3: QA Review

#313 Fix install command wording: url -> http
  assets/i18n/active.en.json
  assets/i18n/active.es.json
  server/builtin/install.go
Labels: 4: Reviews Complete
