Repository mattermost/mattermost-plugin-apps, pull requests merged in 2022-08, with the labels that each got.

#353 fixed the test app
  apps/appclient/mattermost_client.go
  cmd/appsctl/mattermost.go
  test/app/subscriptions.go
Labels: 3: QA Review

#355 MM-43962: Added support for .jar files in appsctl aws
  cmd/appsctl/aws.go
  cmd/appsctl/main.go
  upstream/upaws/client.go
  upstream/upaws/client_lambda.go
  upstream/upaws/provision_app.go
  upstream/upaws/provision_data.go
Labels: 4: Reviews Complete

#354 Update mattermost-server to 7.2, improve circle-ci caching
  .circleci/config.yml
  dev/docker-compose.yml
  go.mod
  go.sum
  plugin.json
  test/e2e/package-lock.json
  test/restapitest/clients.go
Labels: 4: Reviews Complete

#352 Add example Apps in additional languages - Python
  examples/python/README.md
  examples/python/requirements.txt
  examples/python/src/hello-world.py
  examples/python/src/static/icon.png
Labels: 2: Dev Review, Lifecycle/1:stale, 3: QA Review
