Repository mattermost/mattermost-plugin-apps, pull requests merged in 2022-05, with the labels that each got.

#331 #325 feedback: moved WithTimeout to incoming.Request methods
  server/incoming/request.go
  server/proxy/call.go
  server/proxy/install.go
  server/proxy/list.go
Labels: 4: Reviews Complete, QA Deferred

#334 Docker dev environment: Update server version to 6.6
  dev/docker-compose.yml
Labels: 4: Reviews Complete

#332 Create .gitpod.yml
  .gitpod.yml
Labels: 4: Reviews Complete

#337 trim a trailing \n from REST API error responses
  apps/appclient/mattermost_client_pp.go
Labels: 2: Dev Review, QA Deferred

#340 goapp, and use it in REST API tests
  .gitignore
  Makefile
  apps/app.go
  apps/appclient/mattermost_client_pp.go
  apps/call_response.go
  apps/call_test.go
  apps/goapp/app.go
  apps/goapp/awsapp/run.go
  apps/goapp/bindable.go
  apps/goapp/bindable_action.go
  apps/goapp/bindable_action_test.go
  apps/goapp/bindable_form.go
  apps/goapp/bindable_form_test.go
  apps/goapp/bindable_multi.go
  apps/goapp/bindings.go
  apps/goapp/call_request.go
  apps/goapp/call_request_test.go
  apps/goapp/http.go
  apps/goapp/user.go
  apps/locations.go
  apps/log_string_test.go
  apps/manifest.go
  apps/subscription.go
  build/custom.mk
  go.mod
  go.sum
  server/httpin/restapi/app_kv_e2e_test.go
  server/httpin/restapi/app_oauth2_store_e2e_test.go
  server/httpin/restapi/app_subscribe_e2e_test.go
  server/httpin/restapi/restapitestlib.go
  test/restapitest/clients.go
  test/restapitest/echo_test.go
  test/restapitest/helper.go
  test/restapitest/install.go
  test/restapitest/kv_test.go
  test/restapitest/main_test.go
  test/restapitest/oauth2_test.go
  test/restapitest/static/icon.png
  test/restapitest/subscribe_test.go
  utils/mattermost.go
Labels: 2: Dev Review, 3: QA Review, QA Deferred

#335 goapp, expand examples, minor feedback changes
  apps/call_response.go
  apps/goapp/doc.go
  apps/log_string_test.go
  examples/goapp/expand/app.go
  examples/goapp/expand/echo.go
  examples/goapp/expand/static/icon.png
  examples/goapp/expand/user_action.go
  examples/goapp/goapp/app.go
  examples/goapp/goapp/static/icon.png
Labels: 4: Reviews Complete, QA Deferred

#343 Fixed a bad typo/oversight in proxy.GetInstalledApps
  server/proxy/list.go
Labels: 3: QA Review, QA Deferred

#342 disabled MessageHasBeenPosted processing
  .golangci.yml
  apps/subscription.go
  server/appservices/subscriptions.go
  server/mocks/mock_proxy/mock_proxy.go
  server/plugin.go
  server/proxy/notify.go
  server/proxy/notify_test.go
  server/proxy/service.go
  server/store/subscriptions.go
  server/store/subscriptions_test.go
  test/app/subscriptions.go
Labels: 1: PM Review, 3: QA Review, QA Deferred

#344 Style/lint: added unparam to lint
  .golangci.yml
  server/plugin.go
  server/store/session.go
  test/restapitest/kv_test.go
  test/restapitest/oauth2_test.go
  test/restapitest/subscribe_test.go
Labels: 4: Reviews Complete, QA Deferred

#346 /apps debug is now dev mode only, other feedback from DH
  server/builtin/bindings.go
  server/config/config.go
  server/config/config_test.go
  server/proxy/list.go
Labels: 3: QA Review, QA Deferred

#348 [MM-43659] Add missing json tag for Subscription.Call
  apps/subscription.go
Labels: 4: Reviews Complete

#345 Release v1.1.0
  cmd/appsctl/aws.go
  dev/docker-compose.yml
  examples/go/hello-jwt/hello.go
  examples/go/hello-oauth2/hello.go
  examples/go/hello-serverless/manifest.json
  examples/go/hello-webhooks/hello.go
  examples/go/hello-world/hello.go
  examples/goapp/expand/app.go
  examples/goapp/goapp/app.go
  plugin.json
  test/restapitest/echo_test.go
  test/restapitest/kv_test.go
  test/restapitest/oauth2_test.go
  test/restapitest/subscribe_test.go
Labels: 1: PM Review, 2: Dev Review, QA Review Done
