Repository mattermost/mattermost-plugin-apps, pull requests merged in 2022-11, with the labels that each got.

#374 Update golangci-lint version and fix linter errors
  .circleci/config.yml
  .golangci.yml
  apps/binding.go
  apps/goapp/app.go
  apps/package.go
  goapp/expand/user_action.go
  server/builtin/app.go
  server/builtin/install_consent.go
  server/builtin/list.go
  server/httpin/admin.go
  server/httpin/bindings.go
  server/httpin/call.go
  server/httpin/get_ids.go
  server/httpin/kv.go
  server/httpin/service.go
  server/httpin/subscribe.go
  server/incoming/request.go
  server/proxy/expand.go
  server/proxy/form.go
  server/proxy/install.go
  server/store/service.go
  test/app/main.go
  test/app/root.go
  test/hello-world/hello.go
  test/restapitest/admin.go
  test/restapitest/bindings.go
  test/restapitest/clients.go
  test/restapitest/expand.go
  test/restapitest/helper.go
  test/restapitest/notify.go
  test/restapitest/notify_bot_joined_channel.go
  test/restapitest/notify_bot_joined_team.go
  test/restapitest/notify_bot_left_channel.go
  test/restapitest/notify_bot_left_team.go
  test/restapitest/notify_user_left_channel.go
  test/restapitest/notify_user_left_team.go
  test/restapitest/oauth2.go
  upstream/upaws/client_lambda.go
  upstream/upaws/provision_app.go
Labels: 4: Reviews Complete

#381 Move AppMetadataForClient to http layer
  server/httpin/call.go
  server/mocks/mock_proxy/mock_proxy.go
  server/proxy/invoke_call.go
  server/proxy/service.go
  test/restapitest/clients.go
Labels: 4: Reviews Complete

#377 [MM-48054] Don't disable app before uninstalling it
  server/proxy/uninstall.go
Labels: 3: QA Review

#387 Skip TestSingleServer/OAuth2/User_and_bot_calls_can_expand_OAuth2App
  test/restapitest/oauth2.go
Labels: 4: Reviews Complete

#383 Skip TestRESTAPI/bindings/multiple_apps_have_commands
  test/restapitest/bindings.go
Labels: 2: Dev Review

#390 Skip TestRESTAPI/notify/bot_left_team
  test/restapitest/notify_bot_left_team.go
Labels: 2: Dev Review

#398 Include JWT secret in test app startup message
  test/app/main.go
Labels: 2: Dev Review

#395 [MM-48533] Enable color logs
  cmd/appsctl/main.go
  utils/logger.go
Labels: 4: Reviews Complete

#402 Change message when not subscribe to notification (#361)
  server/appservices/subscriptions.go
  test/restapitest/subscribe.go
Labels: 4: Reviews Complete

#400 Test app - Add num_bindings command to set number of bindings in different locations
  test/app/channel_header.go
  test/app/command.go
  test/app/const.go
  test/app/main.go
  test/app/num_bindings.go
  test/app/post_menu.go
Labels: 4: Reviews Complete
