Repository mattermost/mattermost-plugin-apps, pull requests merged in 2022-12, with the labels that each got.

#404 nits/comments: PR feedback for #336
  server/httpin/admin.go
Labels: 2: Dev Review, QA Deferred

#316 [MM-42915] Check if oauth apps are enabled before running any /apps commands
  assets/i18n/active.en.json
  server/builtin/app.go
Labels: 4: Reviews Complete, QA Deferred

#372 [MM-47950] Allow setting developer mode via /apps settings
  assets/i18n/active.en.json
  server/builtin/app.go
  server/builtin/bindings.go
  server/builtin/debug_clean.go
  server/builtin/settings.go
  server/config/config.go
  server/config/config_test.go
  server/config/log_string_test.go
  server/config/service.go
  server/config/test_service.go
  server/plugin.go
  server/plugin_test.go
  server/proxy/expand_test.go
Labels: 4: Reviews Complete, Dev Tester

#359 Ability to force refresh bindings for app after call
  apps/call_response.go
  server/proxy/bindings_test.go
  server/proxy/invoke_call.go
Labels: 4: Reviews Complete, Docs/Done, Dev Tester

#389 Handle HEAD requests for webhook validation
  apps/appclient/mattermost_client_pp.go
  server/httpin/service.go
  server/httpin/webhook.go
  server/proxy/invoke_webhook.go
  server/proxy/service.go
  test/restapitest/main_test.go
  test/restapitest/webhook_auth_test.go
Labels: 4: Reviews Complete, Docs/Needed, Dev Tester

#407 Refresh bindings after setting are saved
  server/builtin/settings.go
Labels: 4: Reviews Complete, Docs/Not Needed

#410 Include caller in logs
  server/httpin/service.go
  server/incoming/request.go
  server/plugin_test.go
  utils/plugin_logger.go
Labels: 2: Dev Review

#408 Update ServiceNow to v0.3.4
  assets/manifests.json
Labels: 4: Reviews Complete, Docs/Not Needed

#409 [MM-48916] Don't try to fet bindings from disabled apps
  server/proxy/invoke_bindings.go
Labels: 4: Reviews Complete

#394 [MM-48538] `/apps debug logs` to stream plugin logs to a Mattermost channel
  assets/i18n/active.en.json
  build/custom.mk
  server/builtin/app.go
  server/builtin/debug.go
  server/builtin/debug_logs.go
  server/config/config.go
  server/config/service.go
  server/config/test_service.go
  server/httpin/service.go
  server/incoming/request.go
  server/mocks/mock_appservices/mock_appservices.go
  server/mocks/mock_config/mock_config.go
  server/mocks/mock_session/mock_session.go
  server/mocks/mock_store/mock_appkv.go
  server/plugin.go
  server/plugin_test.go
  server/proxy/bindings_test.go
  server/proxy/expand_test.go
  server/proxy/notify.go
  server/proxy/service.go
  server/proxy/synchronize.go
  server/session/session_test.go
  server/store/apps.go
  server/store/manifest.go
  server/store/service.go
  utils/plugin_logger.go
Labels: 4: Reviews Complete, Docs/Done, Dev Tester

#413 [MM-49024] Remove v0.7 app manifest workaround
  apps/app.go
  apps/manifest.go
  apps/manifest_json_test.go
  apps/schema_version.go
Labels: 4: Reviews Complete

#380 [MM-47990] Improved app cleanup on uninstall; List fixes
  assets/i18n/active.en.json
  server/appservices/service.go
  server/builtin/app.go
  server/builtin/debug.go
  server/builtin/debug_logs.go
  server/builtin/debug_store_list.go
  server/builtin/debug_store_pollute.go
  server/proxy/uninstall.go
  server/store/appkv.go
  server/store/kv_debug_info.go
  server/store/service.go
  server/store/session.go
  server/store/subscriptions.go
  test/restapitest/uninstall.go
Labels: Docs/Not Needed, Dev Tester

#418 Add tests for webhook paths
  server/proxy/invoke_webhook.go
  test/restapitest/main_test.go
  test/restapitest/webhook_auth_test.go
  test/restapitest/webhook_test.go
Labels: 4: Reviews Complete, AutoMerge

#416 Harden code around disabled apps
  server/mocks/mock_store/mock_app.go
  server/proxy/bindings.go
  server/proxy/invoke_bindings.go
  server/proxy/list.go
  server/proxy/notify.go
  server/proxy/synchronize.go
  server/store/apps.go
  test/restapitest/bindings.go
Labels: 4: Reviews Complete
