Repository mattermost/mattermost-plugin-apps, pull requests merged in 2023-01, with the labels that each got.

#426 [MM-49437] Don't try to ping builtin apps
  server/proxy/list.go
Labels: 4: Reviews Complete

#419 Remove ServiceNow from manifests and add Zendesk
  assets/manifests.json
Labels: 4: Reviews Complete

#424 [MM-49164] Include apps that can be deployed as plugins but aren't in Marketplace response
  server/httpin/admin.go
  server/proxy/list.go
Labels: 4: Reviews Complete

#415 Release v1.2.0
  cmd/appsctl/aws.go
  goapp/expand/app.go
  goapp/hello-world/app.go
  plugin.json
  test/hello-world/hello.go
  test/restapitest/bindings.go
  test/restapitest/echo.go
  test/restapitest/kv.go
  test/restapitest/notify.go
  test/restapitest/oauth2.go
  test/restapitest/subscribe.go
  test/restapitest/uninstall.go
Labels: 4: Reviews Complete

#414 Moved cc log admin to /apps settings
  assets/i18n/active.en.json
  server/builtin/app.go
  server/builtin/debug.go
  server/builtin/debug_logs.go
  server/builtin/install_consent.go
  server/builtin/settings.go
  server/config/config.go
  server/config/log_string_test.go
  server/config/service.go
  server/config/test_service.go
  server/plugin.go
  server/plugin_test.go
  server/proxy/expand_test.go
Labels: 1: PM Review, 4: Reviews Complete

#431 Fix app install flow, more logging
  Makefile
  server/builtin/settings.go
  server/proxy/install.go
Labels: 4: Reviews Complete

#437 [MM-49992] Propagate errors from /ping
  server/proxy/install.go
  server/proxy/invoke_static.go
  server/proxy/list.go
Labels: 4: Reviews Complete

#440 [MM-50054] Fix panic on server with invalid configuration
  server/config/service.go
  server/plugin.go
  server/plugin_test.go
Labels: 4: Reviews Complete, Docs/Not Needed

#438 [MM-49877] Validate call requests paths
  apps/manifest.go
  server/proxy/invoke_call.go
  test/restapitest/call.go
  test/restapitest/main_test.go
Labels: 4: Reviews Complete, Docs/Not Needed

#441 [MM-49946] App Marketplace installs should always be triggered by /apps install listed
  assets/i18n/active.en.json
  assets/i18n/active.es.json
  server/builtin/install.go
Labels: 4: Reviews Complete, Docs/Not Needed

#439 [MM-50056] Rejects manifests with empty DisplayName
  apps/manifest.go
  apps/manifest_test.go
Labels: 4: Reviews Complete, Docs/Done
