Repository mattermost/mattermost-plugin-apps, pull requests merged in 2023-02, with the labels that each got.

#442 [MM-48223] Improve styling of /apps list
  apps/locations.go
  apps/permissions.go
  server/builtin/list.go
Labels: 4: Reviews Complete, Docs/Not Needed, QA Deferred

#447 [MM-49875] [MM-49877] Validate default calls
  server/proxy/invoke_call.go
  test/restapitest/call.go
Labels: 4: Reviews Complete, Docs/Not Needed

#445 [MM-39312] Fail early if MM env variables are not set for appsctl
  cmd/appsctl/aws.go
  cmd/appsctl/mattermost.go
  cmd/appsctl/openfaas.go
  cmd/appsctl/plugin.go
Labels: 4: Reviews Complete, Docs/Not Needed, QA Deferred

#451 [MM-50268] Add additional fields to HTTP logger
  server/httpin/service.go
Labels: 4: Reviews Complete, Docs/Not Needed

#449 [MM-50161] Update dependencies
  .circleci/config.yml
  .golangci.yml
  go.mod
  go.sum
  plugin.json
  server/plugin_test.go
Labels: 4: Reviews Complete, Docs/Not Needed

#452 [MM-50269] Show app icons for disabled apps
  server/httpin/static.go
  server/proxy/invoke_static.go
  test/restapitest/call.go
  test/restapitest/echo.go
  test/restapitest/main_test.go
  test/restapitest/misc.go
  test/restapitest/static.go
Labels: 4: Reviews Complete, Docs/Not Needed, QA Deferred

#432 [MM-49730] Enable bindings call when the OAuthEnabled system setting is false
  server/builtin/app.go
Labels: 4: Reviews Complete, Docs/Not Needed

#454 [MM-49992] Increase ping timeout for lambda functions
  server/proxy/invoke_static.go
  server/proxy/list.go
Labels: 4: Reviews Complete, Docs/Not Needed, QA Deferred

#448 Change homepage_url in plugin.json
  plugin.json
Labels: 1: PM Review, 2: Dev Review

#456 Logging improvement
  server/proxy/bindings.go
  server/proxy/enable.go
  server/proxy/install.go
  server/proxy/invoke_call.go
  utils/mattermost.go
Labels: 4: Reviews Complete, Docs/Not Needed, QA Deferred

#443 MM-48793, MM-48137: improved bot_joined|left_channel|team
  .golangci.yml
  apps/goapp/http.go
  apps/subscription.go
  apps/subscription_test.go
  build/custom.mk
  server/appservices/subscriptions.go
  server/mmclient/client.go
  server/mmclient/http.go
  server/mmclient/rpc.go
  server/mocks/mock_mmclient/mock_mmclient.go
  server/mocks/mock_proxy/mock_expand_getter.go
  server/mocks/mock_store/mock_appstore.go
  server/plugin.go
  server/proxy/expand.go
  server/proxy/expand_getter.go
  server/proxy/expand_test.go
  server/proxy/invoke_call.go
  server/proxy/invoke_webhook.go
  server/proxy/notify.go
  server/proxy/service.go
  server/store/subscriptions.go
  server/store/subscriptions_test.go
  test/app/subscriptions.go
  test/restapitest/clients.go
  test/restapitest/notify.go
  test/restapitest/notify_bot_joined_channel.go
  test/restapitest/notify_bot_joined_team.go
  test/restapitest/notify_bot_left_channel.go
  test/restapitest/notify_bot_left_team.go
  test/restapitest/notify_channel_created.go
  test/restapitest/notify_user_joined_channel.go
  test/restapitest/notify_user_joined_team.go
  test/restapitest/notify_user_left_channel.go
  test/restapitest/notify_user_left_team.go
  test/restapitest/uninstall.go
Labels: 4: Reviews Complete, Docs/Needed, QA Deferred

#375 [MM-48342] Stateful timers
  apps/appclient/mattermost_client.go
  apps/appclient/mattermost_client_pp.go
  apps/path/paths.go
  apps/timer.go
  build/custom.mk
  go.mod
  go.sum
  server/appservices/service.go
  server/appservices/timer.go
  server/httpin/service.go
  server/httpin/timer.go
  server/plugin.go
  server/proxy/service.go
  test/app/command.go
  test/app/const.go
  test/app/main.go
  test/app/subscriptions.go
  test/app/timer.go
Labels: 4: Reviews Complete, Docs/Needed, QA Deferred
